before_install:
    - mkdir -p dependencies
    - wget --output-document=dependencies/cc65.zip https://github.com/cc65/cc65/archive/master.zip
    - (cd dependencies && unzip -q cc65.zip)
    - (cd dependencies/cc65-master && make > /dev/null && sudo make prefix=/usr/local)
language: c
script:
    - make PLATFORM=6502test -j4

