cache:
    directories:
        - cc65-master
before_install:
    - wget https://github.com/cc65/cc65/archive/master.zip
    - unzip -q master.zip
    - cd cc65-master && make > /dev/null && sudo make prefix=/usr/local
language: c
script:
    - make PLATFORM=6502test -j4

