cache:
    directory:
        - dependencies
before_install:
    - sudo add-apt-repository ppa:david.given/ppa -y
    - sudo apt-get update -q
    - sudo apt-get install cc65 sdcc
    - export PATH=$PATH:/usr/local/bin
    - cd ..
language: c
script:
    - make PLATFORM=6502test -j4
    - make PLATFORM=trs80 -j4

